---
- name: check if firewalld is installed
  command: rpm -q firewalld
  register: firewalld_check
  ignore_errors: true

- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
  when: firewalld_check.rc == 0

- name: remove firewalld
  package:
    name: firewalld
    state: absent
